"""fix names

Revision ID: f11291bbfc89
Revises: fe0cb775f9a9
Create Date: 2021-08-05 22:33:13.558493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11291bbfc89'
down_revision = 'fe0cb775f9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id_message', sa.Integer(), nullable=False))
    op.drop_column('messages', 'id_messaage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id_messaage', sa.INTEGER(), nullable=False))
    op.drop_column('messages', 'id_message')
    # ### end Alembic commands ###
